name: CI-CD

on:
  push:
  workflow_dispatch:

jobs:
  CI:
    name: Build da Imagem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.1.5

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da Imagem Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            iadocicco/aula-primeira-pipeline:v${{ github.run_number }}
            iadocicco/aula-primeira-pipeline:latest

  CD-Homolog:
    name: Deploy em Homologação
    needs: [CI]
    uses: iadocicco-ale/primeira-pipeline-cicd/.github/workflows/deploy.yaml@main
    with:
      manifests: |
        k8s/deployment.yaml
      images: |
        iadocicco/aula-primeira-pipeline:v${{ github.run_number }}
      environment: homologacao
    secrets: inherit

  Teste-Ambiente:
    name: Teste de Ambiente
    needs: [CD-Homolog]
    runs-on: ubuntu-latest
    environment: homologacao
    steps:
      - name: Fake Teste
        run: echo "Fake teste de ambiente ${{ vars.APP_NAMESPACE }}"

  CD-Producao:
    name: Deploy em Produção
    needs: [Teste-Ambiente]
    uses: iadocicco-ale/primeira-pipeline-cicd/.github/workflows/deploy.yaml@main
    with:
      manifests: |
        k8s/deployment.yaml
      images: |
        iadocicco/aula-primeira-pipeline:v${{ github.run_number }}
      environment: producao
    secrets: inherit